# NumPy Assignment

# Q1: Find the counts of unique values row-wise

In [2]:
import numpy as np
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

In [4]:
#Output for just above example

[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

In [ ]:
#your code here

Your Output should have 10 columns (numbers from 1 to 10). The values are the counts of the numbers in the respective rows.
For example, Cell(0,8) has the value 2, which means, the number 8 occurs exactly 2 times in the 1st row.

# Q2: Create this pattern of zeros and ones using only slicing approach. Your code must not be more than 6 lines.

In [14]:
#Output

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#your code here

# Q3: Given below a Numpy Array, display odd rows and even columns. you are not allowed to use loop. Do it with slicing.

In [16]:
import numpy
sampleArray = numpy.array([[3 ,8, 9, 11], [15 ,18, 21, 24], 
[27 ,29, 33, 34], [39 ,42, 45, 48], [51 ,52, 57, 53]]) 

Input Array
[[ 3  8  9 11]
 [15 18 21 24]
 [27 29 33 34]
 [39 42 45 48]
 [51 52 57 53]]
Your Output should be: 
[[ 8 11]
 [29 34]
 [52 53]]


In [ ]:
#your code here

# Q4: Detecting all the humps in a 1 Dimentional np array. Humps are values encircled by lower values on both sides. Use NumPy

Input: np.array([1,2,9,1,3,7,1,2,10])

Output: 9, 7

In [ ]:
#your code here